from globals import *
import math
from pathlib import Path

class ProblemInstance:
	def __init__(self, N: int, G: int, S: int, R: int, T: int):
		logger.debug("Began creating the problem instance...")
		self._Init(N, G, S, R, T)
		self._InitOutputFile()
		self._EncodeClauses()
		logger.debug("Finished creating the problem instance.")

	def _Init(self, N: int, G: int, S: int, R: int, T: int, InputFile: Path = None):
		self.N = N
		self.G = G
		self.S = S
		self.R = R
		self.T = T
		if InputFile is None:
			self.OutputFile = DEFAULT_CNF_FILE_PATH
		else:
			self.OutputFile = InputFile

	def _EncodeClauses(self):
		logger.debug("Encoding clauses...")
		self._EncodeOnePlayerPerGroup()
		# TODO: Add the other ones
		logger.debug("Finished encoding clauses")

	def _GetVarID(self, r, p, g) -> int:
		return r * (self.N * self.G) + p * self.G + g + 1

	def _GetClause(self, arr: list[int]) -> str:
		return " ".join(str(x) for x in arr) + " 0\n"

	def _WriteClause(self, arr: list[int]) -> None:
		with open(self.OutputFile, "a") as f:
			f.write(self._GetClause(arr))

	def _GetNumberOfVariables(self) -> int:
		return self.N * self.G * self.R

	def _GetNumberOfClauses(self) -> int:
		# TODO: Find correct count
		onePlayer = 10000
		groupSize = 10000
		pairConstraints = 10000
		return onePlayer + groupSize + pairConstraints

	def _InitOutputFile(self):
		with open(self.OutputFile, "w") as f:
			f.write(f"c Social Golfers Problem CNF generated by https://github.com/Roiqk7/SocialGolfersProblem.git\n")
			# TODO: Check that the numbers are correct
			numVars, numClauses = self._GetNumberOfVariables(), self._GetNumberOfClauses()
			f.write(f"p cnf {numVars} {numClauses}\n")

	def _EncodeOnePlayerPerGroup(self):
		# TODO: Test that it works
		for r in range(self.R):
			for p in range(self.N):
				# at least one group
				clause = [self._GetVarID(r, p, g) for g in range(self.G)]
				self._WriteClause(clause)

				# at most one group
				for g1 in range(self.G):
					for g2 in range(g1 + 1, self.G):
						self._WriteClause(
							[-self._GetVarID(r, p, g1), -self._GetVarID(r, p, g2)])
